@startuml
title sample AIML flowchart
start
switch (発話内容)
case (_)
  switch (input)
  case (その他)
    switch (_fuga)
    case (YES)
      :;
    case (NO)
      :;
    case (その他)
      :どこにもマッチしていません;
    endswitch
  endswitch
case (こんにちは)
  :こんにちは、知りたい内容を発話してください。;
case (今日の天気は？)
  switch (weather)
  case (rain)
    :雨です;
  case (sunny)
    :晴れです;
  case (その他)
    :曇りです;
  endswitch
case (*)
  :別の質問をしてください;
case (#YES or #yes)
  switch (id)
  case (10)
    :メッセージ;
    :[id = 11];
  case (12)
    :12から13になります;
    :[id = 13];
  case ([100)
    :[regex = 100];
  case (その他)
    :正規表現;
  case (その他)
    :その他の条件です;
  endswitch
case (#RELEARN)
  :aaa
                bbb
            
            ここだけ表示させたい
            xxx;
endswitch
stop
@enduml